### ISSUE TITLE
No default pillar values

### ISSUE THREAD

**Issue by babilen** [seegno/influxdb-formula#11]
This formula forces users to always define a pillar even if they are happy to accept the default values. It is also not clear which values **have** to be defined in the pillar and which are optional.

This results in multiple errors such as the following:
```
----------
          ID: influxdb_init
    Function: file.managed
        Name: /etc/init.d/influxdb
      Result: False
     Comment: Unable to manage file: Jinja variable 'dict object' has no attribute 'influxdb'
     Started: 10:24:02.570819
    Duration: 5.532 ms
     Changes: 
```
for various key combinations. Please consider defining a map.jinja in which you set default values that can then be customised via pillars, but allow users to use the formula as-is without additional configuration.

Please refer to https://github.com/saltstack-formulas/salt-formula/blob/master/salt/map.jinja and https://github.com/saltstack-formulas/collectd-formula/blob/master/collectd/map.jinja for inspiration.

**Comment by alfredopalhares** [comment]
@babilen Yes this is true, we would very much accept a pull request to fix this.
